<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>aicontext</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\core\AiContextBuilder.Core.csproj" />
    <ProjectReference Include="..\..\workers\dotnet\AiContextBuilder.Workers.DotNet.csproj" />
  </ItemGroup>

</Project>
