using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using AiPromptContextBuilder.Core.Protocol;

namespace AiPromptContextBuilder.Core.Filters;

public class FilterEvaluation
{
    public bool Allowed { get; set; }
    public ExclusionReason? ExclusionReason { get; set; }
}

public static class EcosystemFilters
{
    private static readonly HashSet<string> ExcludedToolchainAndLockFiles = new(StringComparer.OrdinalIgnoreCase)
    {
        "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "cargo.lock",
        "packages.lock.json", "poetry.lock", "composer.lock", "gemfile.lock",
        "tsconfig.json", "tsconfig.node.json", "tsconfig.app.json", "jsconfig.json",
        ".eslintrc.json", ".eslintrc.js", ".prettierrc", ".editorconfig",
        "bun.lockb", "pubspec.lock"
    };

    private static readonly string[] GeneratedDirs = new[]
    {
        "/obj/", "/bin/", "/dist/", "/build/", "/out/", "/coverage/",
        "/target/", "/target/generated-sources/", "/build/generated/",
        "/__pycache__/", "/.next/", "/.nuxt/", "/.turbo/", "/migrations/",
        "/.dart_tool/", "/vendor/", "/.gradle/", "/CMakeFiles/"
    };

    private static readonly string[] GeneratedSuffixes = new[]
    {
        ".g.cs", ".g.vb", ".generated.cs", ".generated.vb",
        ".designer.cs", ".designer.vb", ".generated.ts", ".generated.js",
        ".min.js", ".min.css", ".map", ".bundle.js", ".chunk.js"
    };

    private static readonly string[] TestDirs = new[]
    {
        "/__tests__/", "/test/", "/tests/", "/src/test/", "/unittests/", "/integrationtests/"
    };

    private static readonly string[] TestSuffixes = new[]
    {
        ".test.ts", ".spec.ts", ".test.tsx", ".spec.tsx", ".test.js", ".spec.js",
        "_test.go", ".tests.cs", ".test.cs", ".unittests.cs",
        "test.java", "tests.java", "testcase.java"
    };

    private static readonly HashSet<string> AssetExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".ico", ".bmp", ".tiff",
        ".mp4", ".webm", ".ogg", ".mp3", ".wav",
        ".woff", ".woff2", ".ttf", ".eot", ".otf",
        ".pdf", ".zip", ".tar", ".gz"
    };

    public static bool IsGeneratedFile(string relativePath, string? fileContent = null)
    {
        string normalized = relativePath.Replace('\\', '/');
        string lower = normalized.ToLowerInvariant();
        string fileName = Path.GetFileName(normalized);

        if (ExcludedToolchainAndLockFiles.Contains(fileName))
            return true;

        if (GeneratedDirs.Any(d => lower.Contains(d) || lower.StartsWith(d.TrimStart('/'))))
            return true;

        if (GeneratedSuffixes.Any(s => lower.EndsWith(s)))
            return true;

        if (!string.IsNullOrEmpty(fileContent))
        {
            string head = fileContent.Length > 500 ? fileContent.Substring(0, 500) : fileContent;
            string headLower = head.ToLowerInvariant();
            if (headLower.Contains("code generated") ||
                headLower.Contains("autogenerated") ||
                headLower.Contains("do not edit") ||
                headLower.Contains("auto-generated"))
            {
                return true;
            }
        }

        return false;
    }

    public static bool IsTestFile(string relativePath)
    {
        string normalized = relativePath.Replace('\\', '/');
        string lower = normalized.ToLowerInvariant();

        if (TestDirs.Any(d => lower.Contains(d) || lower.StartsWith(d.TrimStart('/'))))
            return true;

        if (TestSuffixes.Any(s => lower.EndsWith(s)))
            return true;

        string baseName = Path.GetFileName(lower);
        if (baseName.StartsWith("test_") && baseName.EndsWith(".py")) return true;
        if (baseName.EndsWith("_test.py")) return true;

        return false;
    }

    public static bool IsAssetFile(string relativePath)
    {
        string ext = Path.GetExtension(relativePath);
        return AssetExtensions.Contains(ext);
    }

    public static bool IsConfigFile(string relativePath)
    {
        string ext = Path.GetExtension(relativePath).ToLowerInvariant();
        if (ext is ".json" or ".yaml" or ".yml" or ".toml" or ".ini") return true;

        string baseName = Path.GetFileName(relativePath).ToLowerInvariant();
        return baseName.StartsWith("tsconfig") || baseName.StartsWith("vite.config") || baseName.StartsWith("package.json");
    }

    public static bool MatchesGlob(string relativePath, string globPattern)
    {
        string normalized = relativePath.Replace('\\', '/');
        string regexStr = Regex.Escape(globPattern.Replace('\\', '/'))
            .Replace(@"\*\*", ".*")
            .Replace(@"\*", "[^/]*");
        return Regex.IsMatch(normalized, $"^{regexStr}$", RegexOptions.IgnoreCase);
    }

    /// <summary>
    /// Filter Precedence Evaluation (Section 42):
    /// 1. Root file is always included.
    /// 2. Explicit project, package, namespace, directory exclusions.
    /// 3. Explicit exclude globs.
    /// 4. Explicit include globs.
    /// 5. Generated-file defaults.
    /// 6. Test-file defaults.
    /// 7. Asset defaults.
    /// 8. Configuration-file defaults.
    /// 9. Maximum depth.
    /// </summary>
    public static FilterEvaluation EvaluatePrecedence(
        string relativePath,
        int depth,
        bool isRoot,
        UserConfiguration config,
        string? fileContent = null)
    {
        if (isRoot)
            return new FilterEvaluation { Allowed = true };

        string normalized = relativePath.Replace('\\', '/');

        // 2. Directory & namespace exclusions
        foreach (var dir in config.ExcludedDirectories)
        {
            string normDir = dir.Replace('\\', '/').Trim('/');
            if (normalized.Contains($"/{normDir}/") || normalized.StartsWith($"{normDir}/"))
            {
                return new FilterEvaluation { Allowed = false, ExclusionReason = ExclusionReason.ExcludedNamespace };
            }
        }

        // 3. Exclude globs
        foreach (var glob in config.ExcludeGlobs)
        {
            if (MatchesGlob(normalized, glob))
            {
                return new FilterEvaluation { Allowed = false, ExclusionReason = ExclusionReason.ExcludeGlob };
            }
        }

        // 4. Include globs
        if (config.IncludeGlobs.Count > 0)
        {
            bool matched = config.IncludeGlobs.Any(g => MatchesGlob(normalized, g));
            if (!matched)
            {
                return new FilterEvaluation { Allowed = false, ExclusionReason = ExclusionReason.ExcludeGlob };
            }
        }

        // 5. Generated-file defaults
        if (!config.IncludeGeneratedFiles && IsGeneratedFile(normalized, fileContent))
        {
            return new FilterEvaluation { Allowed = false, ExclusionReason = ExclusionReason.GeneratedFileExcluded };
        }

        // 6. Test-file defaults
        if (!config.IncludeTests && IsTestFile(normalized))
        {
            return new FilterEvaluation { Allowed = false, ExclusionReason = ExclusionReason.TestFileExcluded };
        }

        // 7. Asset defaults
        if (!config.IncludeAssets && IsAssetFile(normalized))
        {
            return new FilterEvaluation { Allowed = false, ExclusionReason = ExclusionReason.AssetExcluded };
        }

        // 8. Configuration-file defaults
        if (!config.IncludeConfigurationFiles && IsConfigFile(normalized))
        {
            return new FilterEvaluation { Allowed = false, ExclusionReason = ExclusionReason.ConfigurationFileExcluded };
        }

        // 9. Maximum depth
        if (config.MaxDepth.HasValue && depth > config.MaxDepth.Value)
        {
            return new FilterEvaluation { Allowed = false, ExclusionReason = ExclusionReason.MaxDepth };
        }

        return new FilterEvaluation { Allowed = true };
    }
}
