import * as path from 'node:path';
import { ExclusionReason, UserConfiguration } from '../protocol/types.js';

export function isGeneratedFile(relativePath: string, fileContent?: string): boolean {
  const normalized = relativePath.replace(/\\/g, '/');
  const lower = normalized.toLowerCase();

  // Directory patterns
  const generatedDirs = [
    '/obj/',
    '/bin/',
    '/dist/',
    '/build/',
    '/out/',
    '/coverage/',
    '/target/',
    '/target/generated-sources/',
    '/build/generated/',
    '/__pycache__/',
    '/.next/',
    '/.nuxt/',
  ];
  if (generatedDirs.some((dir) => lower.includes(dir) || lower.startsWith(dir.slice(1)))) {
    return true;
  }

  // Filename patterns
  const generatedSuffixes = [
    '.g.cs',
    '.g.vb',
    '.generated.cs',
    '.generated.vb',
    '.designer.cs',
    '.designer.vb',
    '.generated.ts',
    '.generated.js',
    '.min.js',
    '.min.css',
    '.map',
  ];
  if (generatedSuffixes.some((suffix) => lower.endsWith(suffix))) {
    return true;
  }

  // Content indicators (first 500 chars)
  if (fileContent) {
    const head = fileContent.slice(0, 500).toLowerCase();
    if (
      head.includes('code generated') ||
      head.includes('autogenerated') ||
      head.includes('do not edit') ||
      head.includes('auto-generated')
    ) {
      return true;
    }
  }

  return false;
}

export function isTestFile(relativePath: string): boolean {
  const normalized = relativePath.replace(/\\/g, '/');
  const lower = normalized.toLowerCase();

  // Test directories
  const testDirs = [
    '/__tests__/',
    '/test/',
    '/tests/',
    '/src/test/',
    '/unittests/',
    '/integrationtests/',
  ];
  if (testDirs.some((dir) => lower.includes(dir) || lower.startsWith(dir.slice(1)))) {
    return true;
  }

  // File suffix patterns
  const testSuffixes = [
    '.test.ts',
    '.spec.ts',
    '.test.tsx',
    '.spec.tsx',
    '.test.js',
    '.spec.js',
    '_test.go',
    '.tests.cs',
    '.test.cs',
    '.unittests.cs',
    'test.java',
    'tests.java',
    'testcase.java',
  ];
  if (testSuffixes.some((s) => lower.endsWith(s))) {
    return true;
  }

  const baseName = path.basename(lower);
  if (baseName.startsWith('test_') && baseName.endsWith('.py')) return true;
  if (baseName.endsWith('_test.py')) return true;

  return false;
}

export function isAssetFile(relativePath: string): boolean {
  const ext = path.extname(relativePath).toLowerCase();
  const assetExts = [
    '.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp', '.ico', '.bmp', '.tiff',
    '.mp4', '.webm', '.ogg', '.mp3', '.wav',
    '.woff', '.woff2', '.ttf', '.eot', '.otf',
    '.pdf', '.zip', '.tar', '.gz',
  ];
  return assetExts.includes(ext);
}

export function isConfigFile(relativePath: string): boolean {
  const base = path.basename(relativePath).toLowerCase();
  const ext = path.extname(relativePath).toLowerCase();
  if (ext === '.json' || ext === '.yaml' || ext === '.yml' || ext === '.toml' || ext === '.ini') {
    return true;
  }
  return base.startsWith('tsconfig') || base.startsWith('vite.config') || base.startsWith('package.json');
}

/**
 * Basic glob matcher supporting * and ** wildcard syntax
 */
export function matchesGlob(relativePath: string, globPattern: string): boolean {
  const normalized = relativePath.replace(/\\/g, '/');
  const regexStr = globPattern
    .replace(/\\/g, '/')
    .replace(/\./g, '\\.')
    .replace(/\*\*/g, '§§')
    .replace(/\*/g, '[^/]*')
    .replace(/§§/g, '.*');
  const regex = new RegExp(`^${regexStr}$`, 'i');
  return regex.test(normalized);
}

export interface FilterEvaluation {
  allowed: boolean;
  exclusionReason?: ExclusionReason;
}

/**
 * Filter precedence evaluation (Section 42):
 * 1. Root file is always included.
 * 2. Explicit project, package, namespace, and directory exclusions.
 * 3. Explicit exclude globs.
 * 4. Explicit include globs.
 * 5. Generated-file defaults.
 * 6. Test-file defaults.
 * 7. Asset defaults.
 * 8. Configuration-file defaults.
 * 9. Maximum depth.
 */
export function evaluateFilterPrecedence(
  relativePath: string,
  depth: number,
  isRoot: boolean,
  config: UserConfiguration,
  fileContent?: string
): FilterEvaluation {
  // 1. Root file is always included
  if (isRoot) {
    return { allowed: true };
  }

  const normalized = relativePath.replace(/\\/g, '/');

  // 2. Explicit directory exclusions
  for (const dir of config.excludedDirectories) {
    const normDir = dir.replace(/\\/g, '/').replace(/^\/|\/$/g, '');
    if (normalized.includes(`/${normDir}/`) || normalized.startsWith(`${normDir}/`)) {
      return { allowed: false, exclusionReason: 'ExcludedNamespace' }; // directory/namespace
    }
  }

  // 3. Explicit exclude globs
  for (const glob of config.excludeGlobs) {
    if (matchesGlob(normalized, glob)) {
      return { allowed: false, exclusionReason: 'ExcludeGlob' };
    }
  }

  // 4. Explicit include globs (if provided, must match at least one)
  if (config.includeGlobs.length > 0) {
    const matched = config.includeGlobs.some((g) => matchesGlob(normalized, g));
    if (!matched) {
      return { allowed: false, exclusionReason: 'ExcludeGlob' };
    }
  }

  // 5. Generated file defaults
  if (!config.includeGeneratedFiles && isGeneratedFile(normalized, fileContent)) {
    return { allowed: false, exclusionReason: 'GeneratedFileExcluded' };
  }

  // 6. Test file defaults
  if (!config.includeTests && isTestFile(normalized)) {
    return { allowed: false, exclusionReason: 'TestFileExcluded' };
  }

  // 7. Asset defaults
  if (!config.includeAssets && isAssetFile(normalized)) {
    return { allowed: false, exclusionReason: 'AssetExcluded' };
  }

  // 8. Configuration file defaults
  if (!config.includeConfigurationFiles && isConfigFile(normalized)) {
    return { allowed: false, exclusionReason: 'ConfigurationFileExcluded' };
  }

  // 9. Maximum depth
  if (config.maxDepth !== null && config.maxDepth !== undefined && depth > config.maxDepth) {
    return { allowed: false, exclusionReason: 'MaxDepth' };
  }

  return { allowed: true };
}
